/*
 * H_KeyPad_CFG.h
 *
 *  Created on: Sep 5, 2024
 *      Author: Nourhan Mohamed Hassan
 */

#ifndef HAL_H_KEYPAD_DRIVER_H_KEYPAD_CFG_H_
#define HAL_H_KEYPAD_DRIVER_H_KEYPAD_CFG_H_

#define KEYPAD_COL_PORT PORT_A
#define KEYPAD_COL_PIN0 PIN0
#define KEYPAD_COL_PIN1 PIN1
#define KEYPAD_COL_PIN2 PIN2
#define KEYPAD_COL_PIN3 PIN3

#define KEYPAD_ROW_PORT PORT_A
#define KEYPAD_ROW_PIN0 PIN0
#define KEYPAD_ROW_PIN1 PIN1
#define KEYPAD_ROW_PIN2 PIN2
#define KEYPAD_ROW_PIN3 PIN3


#endif /* HAL_H_KEYPAD_DRIVER_H_KEYPAD_CFG_H_ */
